version: '0.5'

services:
  scraper:
    build: .
    environment:
      DB_URL: mysql+mysqlconnector://user:password@db/payment_db
      LOGIN_URL: https://your-portal.com/login
      USERNAME: your_username
      PASSWORD: your_password
      EXPORT_URL: https://your-portal.com/export

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
