version: '0.5'

services:
  scraper:
    build: .
    environment:
      DB_URL: ${DB_URL}
      LOGIN_URL: ${LOGIN_URL}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      EXPORT_URL: ${EXPORT_URL}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
